definitions:
  scripts:
    - &echo_with_substitution
      name: Echo with substitution using the bash way
      script: |
        echo $(whoami)
        echo $(flutter version)


workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: 12.4
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build apk --debug
      - find . -name "Podfile" -execdir pod install \;
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

  tests-only:
    name: Tests only with PR trigger
    max_build_duration: 10
    instance_type: linux
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: false
        - pattern: test
          include: true
          source: false
    when:
      changeset:
        includes:
          - 'android/'
        excludes:
          - '**/.gitignore'
    scripts:
      - flutter packages pub get
    artifacts:
      - flutter_drive.log

  quick-cache-test:
    name: quick cache test
    max_build_duration: 3
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    instance_type: mac_mini
    environment:
      xcode: 12.4

  cache-bomb:
    name: cache bomb theory test
    max_build_duration: 120
    cache:
      cache_paths:
        - $HOME/itsabomb
    instance_type: mac_mini
    environment:
      xcode: 12.4
    scripts:
      - |
        mkdir $HOME/itsabomb
        sudo dd if=/dev/random of=$HOME/itsabomb/boom bs=1024 count=10485760

  test-debug-macos:
    name: Test debug build on macOS
    max_build_duration: 30
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    environment:
      xcode: 12.4
    scripts:
      - flutter --version

  test-emulator-linux:
    name: Tests Android emulator under linux
    max_build_duration: 10
    scripts:
      - |
        flutter emulators --launch emulator
        adb wait-for-device
        adb devices
          
  test-flutter-stable-linux:
    name: Test flutter stable on Linux
    max_build_duration: 3
    instance_type: linux
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - flutter --version

  sleep-well-macos:
    name: 2h sleep on macOS
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      groups:
        - test
      xcode: 12.5
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    scripts:
      - sleep 7200

  sleep-well-linux:
    name: 2h sleep on Linux
    environment:
      groups:
        - test
    max_build_duration: 120
    instance_type: linux
    scripts:
      - ssh-add -L
      - sleep 7200

  sleep-well-windows:
    name: 2h sleep on Windows
    environment:
      groups:
        - test
    max_build_duration: 120
    instance_type: windows_x2
    scripts:
      - ssh-add -L
      - sleep 7200

  test-flutter-stable-macos:
    name: Test flutter stable on macOS
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      xcode: latest
    scripts:
      - flutter --version

  test-flutter-1.22.6-linux:
    name: Test flutter 1.22.6 on Linux
    max_build_duration: 3
    instance_type: linux
    environment:
      flutter: 1.22.6
    scripts:
      - flutter --version

  test-flutter-1.22.6-macos:
    name: Test flutter 1.22.6 on macOS
    max_build_duration: 3
    # instance_type: mac_mini
    environment:
      xcode: 12.4
      flutter: 1.22.6
    scripts:
      - flutter --version

  ndk-test:
    name: Test custom NDK version
    instance_type: mac_pro
    environment:
      xcode: 13
      ndk: r22b
    scripts:
      - echo "Build"

  pyenv-test:
    name: Try temp fix for pyenv
    instance_type: linux
    environment:
      vars:
        PYENV_ROOT: "/home/builder/.pyenv"
        PYENV_SHELL: "zsh"
    scripts:
      - name: Try py3.6 venv
        script: |
          export PATH=/home/builder/.pyenv/bin:$PATH
          pyenv install 3.6.12
          pyenv local 3.6.12
          pyenv exec python -m venv venv
          source venv/bin/activate
          python -V
